# DPAT Training Configuration

# Data paths
data:
  train_data_path: "data/miRAW_Train_Validation.txt"
  cache_dir: "cache"
  
# Model parameters
model:
  alignment_config:
    input_channels: 10
    output_channels: 256
    hidden_channels: 128
    kernel_sizes: [1, 3, 5, 7]
    use_se: true
    use_cbam: true
  
  semantic_config:
    bert_model_name: "multimolecule/rnabert"
    bert_hidden_size: 768
    conv_hidden_size: 1024
    lstm_hidden_size: 128
    proj_dim: 256
    freeze_bert: false
  
  fusion_config:
    embed_dim: 256
    num_heads: 8
    use_gate: true
  
  num_classes: 1
  dropout: 0.1
  use_simple_semantic: false

# Training parameters
training:
  batch_size: 32
  learning_rate: 0.001
  bert_learning_rate: 0.00001
  num_epochs: 100
  warmup_steps: 1000
  max_grad_norm: 1.0
  
# Data processing
data_processing:
  window_size: 40
  seed_length: 12
  alignment_threshold: 6
  max_length: 50
  max_bert_length: 512

# Training settings
training_settings:
  early_stopping_patience: 10
  save_top_k: 3
  use_amp: true
  accumulate_grad_batches: 1
  
# Paths
paths:
  checkpoint_dir: "checkpoints"
  log_dir: "runs"
  
# Hardware
hardware:
  num_workers: 0
  pin_memory: true
  
# Logging
logging:
  log_every_n_steps: 100
  val_check_interval: 1.0
  
# Seed
seed: 42 